name: Restart stopped workflows

on:
  schedule:
    - cron:  '15 * * * *'
jobs:
  run:
    name: Restart stopped workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        name: Cache dependencies
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python app.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit
        run: |
          git config --global user.email "57559326+codeforIATIbot@users.noreply.github.com"
          git config --global user.name "Code for IATI bot"
          git commit --amend --no-edit
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          force: true
