name: Restart stopped workflows

on:
  push:
    branches:
      - main

  schedule:
    - cron:  '0 */6 * * *'

jobs:
  run:
    name: Restart stopped workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python app.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit
        run: |
          git config --global user.email "57559326+codeforIATIbot@users.noreply.github.com"
          git config --global user.name "Code for IATI bot"
          git commit --amend --no-edit
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          force: true
